In [3]:
from datasets import load_from_disk
import numpy as np
from tqdm import tqdm


/home/elena/miniconda/envs/emcomm/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
npz_path = {}
npz_path[3] = f"/home/elena/emcomm/emcomm_captions/epoch_datasets/epoch_0000/data.npz"
# npz_path[5] = f"../../../datasets/coco_npz/coco_full_train_val_152_resnet_5_distractors.npz"


In [5]:
# load each file and print some info
loaded = {}
for k, path in npz_path.items():
    print(f"\nloading key={k} from {path}")
    loaded[k] = np.load(path)
    print("  contained arrays:", loaded[k].files)
    for name in loaded[k].files:
        arr = loaded[k][name]
        print(f"    {name}: shape {arr.shape}, dtype {arr.dtype}")
# `loaded` now holds the opened npz objects for further exploration


loading key=3 from /home/elena/emcomm/emcomm_captions/epoch_datasets/epoch_0000/data.npz
  contained arrays: ['train']


BadZipFile: Bad CRC-32 for file 'train.npy'

In [4]:
loaded[3]['train']

array([[[-1.0080241 , -1.80739784, -1.49478912, ...,  6.16224146,
          2.68395805,  1.86447883],
        [-1.55413079, -1.59470248, -1.16874933, ..., -2.09930706,
          4.49808073, -1.24141407],
        [-2.48747325,  0.69393975,  0.08386278, ...,  0.24491017,
          0.28416002,  2.60658884],
        [-3.42495155,  2.38992453, -3.8109293 , ...,  3.86413431,
          2.2647593 ,  0.56530631]],

       [[ 0.01889494, -2.37212038,  0.62854952, ..., -1.69000411,
          1.4087069 , -2.33617878],
        [-5.75670338,  2.95506167, -2.861588  , ...,  0.44920707,
          1.71828067, -0.6712482 ],
        [-1.66239786,  1.59194636, -0.66137797, ..., -1.3785795 ,
         -0.27419019,  8.03960323],
        [-1.70616519, -1.98111737,  2.7083745 , ..., -4.41854477,
          0.81618726, -1.67216349]],

       [[-3.96929121, -2.66328144, -0.65721798, ..., -4.58062744,
         -1.5304358 ,  2.50141478],
        [ 3.49858856, -1.9949708 , -0.69162804, ...,  0.13957536,
          0.

In [5]:
loaded[3]['train'].shape, loaded[3]['train_labels'].shape

((118287, 4, 1000), (118287,))

In [6]:
loaded[5]['train'].shape, loaded[3]['train_labels'].shape

((118287, 6, 1000), (118287,))

In [17]:
i = 42
dp_3, dp_l_3 = loaded[3]['train'][i], loaded[3]['train_labels'][i]

In [18]:
dp_5, dp_l_5 = loaded[5]['train'][i], loaded[5]['train_labels'][i]

In [19]:
dp_3, dp_l_3

(array([[ 2.26784635, -1.76656199, -0.71614814, ...,  4.06540108,
          1.39725721,  0.42973429],
        [-5.99095631, -1.272856  , -0.87928236, ..., -3.85132003,
          0.99815524,  9.03001308],
        [-1.11139393, -0.21315941, -2.46269584, ..., -1.95495272,
          1.82696164, -1.26922965],
        [-1.52243686,  1.08138466, -1.23674655, ..., -0.75664234,
         -0.67569184,  3.0899117 ]], shape=(4, 1000)),
 np.int64(1))

In [ ]:
dp_5, dp_l_5 # >> THE TARGETS ARE THE SAME

(array([[ 0.45287564, -0.97806847,  2.0348506 , ..., -1.56270373,
          0.06049746,  1.75106025],
        [-3.18200636, -3.30122113,  0.74590707, ..., -3.99651837,
         -1.1724    ,  2.246629  ],
        [-2.89191532, -1.05334282, -3.61855888, ...,  2.34986091,
          0.28425059,  1.92006505],
        [-5.99095631, -1.272856  , -0.87928236, ..., -3.85132003,
          0.99815524,  9.03001308],
        [-2.95219994, -2.35028219,  1.39732623, ..., -1.76098788,
          1.72788429, -0.54156452],
        [ 0.28448945, -2.43070936,  1.15952754, ..., -1.47912312,
         -0.06929657, -0.5086602 ]], shape=(6, 1000)),
 np.int64(3))